1. Download webiste: https://ich-tanke.de/tankstellen/super-e5/ort/herzogenrath/
2. Scrape data of gas stations
3. Make a program which automaticaly downloads the prices every 5 min
4. Analyse

In [1]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from datetime import datetime

In [2]:
time = str(datetime.now().strftime("%Y-%m-%d(%H:%M)"))
print(time)

2022-12-13(17:49)

In [3]:
#1. Get html website
url="https://ich-tanke.de/tankstellen/super-e10/ort/herzogenrath/"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'}
response = requests.get(url, headers=headers)
file_name = "herzogenrath{}.html".format(str(datetime.now().strftime("%Y-%m-%d,%H.%M")))
with open(file_name, mode='wb') as file:
    file.write(response.content)

In [4]:
#open website with bs4
with open(file_name, encoding='utf-8') as file:
    soup = BeautifulSoup(file, "lxml")

In [5]:
#first_entry = soup.find_all("div" , {id:"colm"})
content_page = soup.find(id="colm").find_all("li")

content_page[0].find("em")['title']

'letzte Preisänderung: 13.12.2022, 17:22 Uhr'

In [6]:
#looping to all gasstation content and saving info to list
content_page = soup.find(id="colm").find_all("li")
now_time = datetime.now()

df_list = []
for t in content_page:
    station_id = t["id"]
    station_name = t.find_all("a")[0].contents[0]
    street_loc =t.find_all("div")[1].find_all('p')[0].contents[0][:-len(" · ")]
    city = t.find_all("div")[1].find_all('p')[0].find("a").contents[0]
    price = t.find("span", title="Preisangabe in Euro").contents[0]
    is24_7 = True if len(t.find_all("div")[1].find_all('p')[1].contents) != 1 else False
    
    df_list.append({"station_id": station_id, 
                    "station_name": station_name, 
                    "street":street_loc, 
                    "city": city, 
                    "price": price, 
                    "24/7":is24_7, 
                    "price_time": t.find("em")["title"][len("letzte Preisänderung: "):-4],
                    "download_time":now_time })
df3 = pd.DataFrame(df_list)

In [159]:
df

,station_id,station_name,street,city,price,24/7
0,tankstelle-da000cb481962aaeb0ab34b87edaec58,ARAL,Roermonder Straße 25-29,52134 Herzogenrath,"1,79",True
1,tankstelle-b46f9f36da083380dc8e42ba7ec69a13,Shell,Voccartstraße 28,52134 Herzogenrath,"1,81",True
2,tankstelle-c4013858ca406f4c9612961b5e615ab2,T,Geilenkirchener Straße 414,52134 Herzogenrath,"×,××",False
3,tankstelle-492a0297c2f948db922bf72aaa7abbb0,bft,Voccartstraße 77,52134 Herzogenrath,"×,××",False
4,tankstelle-d9e956ea95aea36cc29d08ffb2d8c5fc,TotalEnergies,Voccartstraße 80,52134 Herzogenrath,"×,××",False
5,tankstelle-90b52a27c5d279ec651e651be2815432,PM,Kirchrather Straße 110-112,52134 Herzogenrath,"×,××",False
6,tankstelle-714b08238cd51dac80e36fed5d7025e5,Shell,Erkensstraße 2-4,52134 Herzogenrath,"×,××",False

In [178]:
df2

,station_id,station_name,street,city,price,24/7,price_time,download_time
0,tankstelle-492a0297c2f948db922bf72aaa7abbb0,bft,Voccartstraße 77,52134 Herzogenrath,"1,56",False,"11.12.2022, 07:26",2022-12-11 21:07:48.686162
1,tankstelle-c4013858ca406f4c9612961b5e615ab2,T,Geilenkirchener Straße 414,52134 Herzogenrath,"1,57",False,"11.12.2022, 08:29",2022-12-11 21:07:48.686162
2,tankstelle-da000cb481962aaeb0ab34b87edaec58,ARAL,Roermonder Straße 25-29,52134 Herzogenrath,"1,57",True,"11.12.2022, 08:30",2022-12-11 21:07:48.686162
3,tankstelle-d9e956ea95aea36cc29d08ffb2d8c5fc,TotalEnergies,Voccartstraße 80,52134 Herzogenrath,"1,59",False,"11.12.2022, 09:10",2022-12-11 21:07:48.686162
4,tankstelle-90b52a27c5d279ec651e651be2815432,PM,Kirchrather Straße 110-112,52134 Herzogenrath,"1,62",False,"11.12.2022, 09:18",2022-12-11 21:07:48.686162
5,tankstelle-b46f9f36da083380dc8e42ba7ec69a13,Shell,Voccartstraße 28,52134 Herzogenrath,"1,63",True,"11.12.2022, 09:02",2022-12-11 21:07:48.686162
6,tankstelle-714b08238cd51dac80e36fed5d7025e5,Shell,Erkensstraße 2-4,52134 Herzogenrath,"1,64",False,"11.12.2022, 09:02",2022-12-11 21:07:48.686162

In [205]:
df3

,station_id,station_name,street,city,price,24/7,price_time,download_time
0,tankstelle-b46f9f36da083380dc8e42ba7ec69a13,Shell,Voccartstraße 28,52134 Herzogenrath,"1,62",True,"11.12.2022, 22:05",2022-12-12 00:44:04.811870
1,tankstelle-da000cb481962aaeb0ab34b87edaec58,ARAL,Roermonder Straße 25-29,52134 Herzogenrath,"1,65",True,"11.12.2022, 22:05",2022-12-12 00:44:04.811870
2,tankstelle-492a0297c2f948db922bf72aaa7abbb0,bft,Voccartstraße 77,52134 Herzogenrath,"×,××",False,"11.12.2022, 20:10",2022-12-12 00:44:04.811870
3,tankstelle-c4013858ca406f4c9612961b5e615ab2,T,Geilenkirchener Straße 414,52134 Herzogenrath,"×,××",False,"11.12.2022, 21:08",2022-12-12 00:44:04.811870
4,tankstelle-d9e956ea95aea36cc29d08ffb2d8c5fc,TotalEnergies,Voccartstraße 80,52134 Herzogenrath,"×,××",False,"11.12.2022, 20:00",2022-12-12 00:44:04.811870
5,tankstelle-90b52a27c5d279ec651e651be2815432,PM,Kirchrather Straße 110-112,52134 Herzogenrath,"×,××",False,"11.12.2022, 23:05",2022-12-12 00:44:04.811870
6,tankstelle-714b08238cd51dac80e36fed5d7025e5,Shell,Erkensstraße 2-4,52134 Herzogenrath,"×,××",False,"11.12.2022, 22:05",2022-12-12 00:44:04.811870

In [7]:
df3

,station_id,station_name,street,city,price,24/7,price_time,download_time
0,tankstelle-90b52a27c5d279ec651e651be2815432,PM,Kirchrather Straße 110-112,52134 Herzogenrath,"1,55",False,"13.12.2022, 17:22",2022-12-13 17:50:00.029920
1,tankstelle-c4013858ca406f4c9612961b5e615ab2,T,Geilenkirchener Straße 414,52134 Herzogenrath,"1,57",False,"13.12.2022, 17:26",2022-12-13 17:50:00.029920
2,tankstelle-714b08238cd51dac80e36fed5d7025e5,Shell,Erkensstraße 2-4,52134 Herzogenrath,"1,57",False,"13.12.2022, 17:26",2022-12-13 17:50:00.029920
3,tankstelle-b46f9f36da083380dc8e42ba7ec69a13,Shell,Voccartstraße 28,52134 Herzogenrath,"1,58",True,"13.12.2022, 17:12",2022-12-13 17:50:00.029920
4,tankstelle-492a0297c2f948db922bf72aaa7abbb0,bft,Voccartstraße 77,52134 Herzogenrath,"1,59",False,"13.12.2022, 17:42",2022-12-13 17:50:00.029920
5,tankstelle-d9e956ea95aea36cc29d08ffb2d8c5fc,TotalEnergies,Voccartstraße 80,52134 Herzogenrath,"1,60",False,"13.12.2022, 17:25",2022-12-13 17:50:00.029920
6,tankstelle-da000cb481962aaeb0ab34b87edaec58,ARAL,Roermonder Straße 25-29,52134 Herzogenrath,"1,61",True,"13.12.2022, 17:08",2022-12-13 17:50:00.029920

In [11]:
df3.to_csv("GasPrices_"+str(datetime.now().strftime("%Y-%m-%d,%H.%M")))